<a href="https://colab.research.google.com/github/mari-azevedo/manipulando_base_de_dados/blob/main/Manipulando_base_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulando base de dados

In [1]:
import gdown
import pandas as pd

url = 'https://drive.google.com/uc?id=1R1nvX6MocByvYBvMs5ujUhbdpW0gRe_X'
output = 'dados_credito.csv'
gdown.download(url, output, quiet=False)

credito = pd.read_csv('/content/dados_credito.csv', sep=';', decimal=',')
credito.head(10)

Downloading...
From: https://drive.google.com/uc?id=1R1nvX6MocByvYBvMs5ujUhbdpW0gRe_X
To: /content/dados_credito.csv
100%|██████████| 3.39k/3.39k [00:00<00:00, 6.61MB/s]

,id,limites,sexo,escolaridade,status_civil,xxxxx_idade_errorrrrrrrrrr,pagamento,valor_divida,valor_pago
0,1,20000.0,2.0,2.0,1.0,24.0,2.0,3913.0,0.0
1,2,120000.0,2.0,2.0,2.0,26.0,-1.0,2682.0,0.0
2,3,90000.0,2.0,2.0,2.0,34.0,0.0,29239.0,1518.0
3,4,50000.0,2.0,2.0,1.0,37.0,0.0,46990.0,2000.0
4,5,50000.0,1.0,2.0,1.0,57.0,-1.0,8617.0,2000.0
5,6,50000.0,1.0,1.0,2.0,37.0,0.0,64400.0,2500.0
6,7,500000.0,1.0,1.0,2.0,29.0,0.0,367965.0,55000.0
7,8,100000.0,2.0,2.0,2.0,23.0,0.0,11876.0,380.0
8,9,140000.0,2.0,3.0,1.0,28.0,0.0,11285.0,3329.0
9,10,20000.0,1.0,3.0,2.0,35.0,-2.0,0.0,0.0

Verificando e corrigindo os nomes das colunas

In [2]:
print('Antes:',credito.columns)
credito.columns = ['id', 'limites', 'sexo', 'escolaridade', 'status_civil', 'idade', 'pagamento', 'valor_divida', 'valor_pago']
print('Depois:',credito.columns)

Antes: Index(['id', 'limites', 'sexo', 'escolaridade', 'status_civil',
       'xxxxx_idade_errorrrrrrrrrr', 'pagamento', 'valor_divida',
       'valor_pago'],
      dtype='object')
Depois: Index(['id', 'limites', 'sexo', 'escolaridade', 'status_civil', 'idade',
       'pagamento', 'valor_divida', 'valor_pago'],
      dtype='object')

Verificando e removando valores faltantes no banco

In [3]:
print( 'Antes:',credito.shape)
print( 'Linhas com valores faltantes:',credito[credito.isna().any(axis=1)].shape)
display(credito[credito.isna().any(axis=1)])
credito = credito.dropna(how='any')
print( 'Depois de remover:',credito.shape)

Antes: (60, 9)
Linhas com valores faltantes: (10, 9)

,id,limites,sexo,escolaridade,status_civil,idade,pagamento,valor_divida,valor_pago
50,51,70000.0,1.0,3.0,2.0,42.0,1.0,37042.0,NaN
51,52,NaN,2.0,3.0,3.0,43.0,0.0,61559.0,2000.0
52,53,310000.0,2.0,NaN,1.0,49.0,-2.0,13465.0,7875.0
53,54,180000.0,2.0,1.0,2.0,25.0,1.0,NaN,1300.0
54,55,NaN,2.0,1.0,2.0,29.0,2.0,46224.0,1600.0
55,56,500000.0,NaN,1.0,1.0,45.0,-2.0,1905.0,3640.0
56,57,180000.0,2.0,NaN,1.0,34.0,0.0,16386.0,8500.0
57,58,180000.0,2.0,2.0,1.0,34.0,0.0,NaN,8083.0
58,59,200000.0,2.0,1.0,2.0,34.0,-1.0,1587.0,NaN
59,60,400000.0,2.0,2.0,1.0,29.0,0.0,400134.0,NaN

Depois de remover: (50, 9)

As variáveis limites, valor_divida e valor_pago estão em dólar taiwanês.
Assumi que cada dólar taiwânes valha R$0,20. Transformei essas variáveis para que o valor esteja em reais (moeda)

In [4]:
print("DataFrame original:")
print(credito[['limites', 'valor_divida','valor_pago']].head(5))
credito.loc[:,['limites','valor_divida','valor_pago']] *= 0.2
print("\nDataFrame atualizado:")
print(credito[['limites', 'valor_divida','valor_pago']].head(5))

DataFrame original:
    limites  valor_divida  valor_pago
0   20000.0        3913.0         0.0
1  120000.0        2682.0         0.0
2   90000.0       29239.0      1518.0
3   50000.0       46990.0      2000.0
4   50000.0        8617.0      2000.0

DataFrame atualizado:
   limites  valor_divida  valor_pago
0   4000.0         782.6         0.0
1  24000.0         536.4         0.0
2  18000.0        5847.8       303.6
3  10000.0        9398.0       400.0
4  10000.0        1723.4       400.0

O banco estava codificado. Criei variáveis que traduziram os códigos. No banco de dados "credito", criei as seguintes variáveis:

###sexo2:
Se sexo = 1, então sexo2 = Masculino
Se sexo = 2, então sexo2 = Feminino

###escolaridade2:
Se escolaridade <= 2, então escolaridade2 = Ensino superior ou maior
Se escolaridade >= 3, então escolaridade2 = Ensino médio ou menor

### status_civil2:
Se status_civil = 1, então status_civil2 = Casado(a)
Se status_civil = 2, então status_civil2 = Solteiro(a)
Se status_civil = 3, então status_civil2 = Outros

### pagamento2:
Se pagamento < 0, então pagamento2 = Antecipado
Se pagamento = 0, então pagamento2 = Em dia
Se pagamento > 0, então pagamento2 = Atrasado

In [5]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.25.2)

In [6]:
import numpy as np

# Definindo as condições e os valores
condições_sexo2 = [(credito['sexo']== 1),(credito['sexo']== 2)]
valores_sexo2 = ["Masculino","Feminino"]

condições_escolaridade2 = [(credito['escolaridade']<=2),(credito['escolaridade']>=3)]
valores_escolaridade2 = ["Ensino superior ou maior", "Ensino medio ou menor"]

condições_civil2 = [(credito['status_civil']==1),(credito['status_civil']==2),(credito['status_civil']==3)]
valores_civil2 = ["Casado(a)","Solteiro(a)","Outros"]

condições_pagamento2 = [(credito['pagamento']<0),(credito['pagamento']==0),(credito['pagamento']>0)]
valores_pagamento2 = ["Antecipado","Em dia","Atrasado"]

# Adicionando as colunas
credito['sexo2'] = np.select(condições_sexo2, valores_sexo2)
credito['escolaridade2'] = np.select(condições_escolaridade2, valores_escolaridade2)
credito['status_civil2'] = np.select(condições_civil2, valores_civil2)
credito['pagamento2'] = np.select(condições_pagamento2, valores_pagamento2)

# Imprimindo
credito.head(10)

,id,limites,sexo,escolaridade,status_civil,idade,pagamento,valor_divida,valor_pago,sexo2,escolaridade2,status_civil2,pagamento2
0,1,4000.0,2.0,2.0,1.0,24.0,2.0,782.6,0.0,Feminino,Ensino superior ou maior,Casado(a),Atrasado
1,2,24000.0,2.0,2.0,2.0,26.0,-1.0,536.4,0.0,Feminino,Ensino superior ou maior,Solteiro(a),Antecipado
2,3,18000.0,2.0,2.0,2.0,34.0,0.0,5847.8,303.6,Feminino,Ensino superior ou maior,Solteiro(a),Em dia
3,4,10000.0,2.0,2.0,1.0,37.0,0.0,9398.0,400.0,Feminino,Ensino superior ou maior,Casado(a),Em dia
4,5,10000.0,1.0,2.0,1.0,57.0,-1.0,1723.4,400.0,Masculino,Ensino superior ou maior,Casado(a),Antecipado
5,6,10000.0,1.0,1.0,2.0,37.0,0.0,12880.0,500.0,Masculino,Ensino superior ou maior,Solteiro(a),Em dia
6,7,100000.0,1.0,1.0,2.0,29.0,0.0,73593.0,11000.0,Masculino,Ensino superior ou maior,Solteiro(a),Em dia
7,8,20000.0,2.0,2.0,2.0,23.0,0.0,2375.2,76.0,Feminino,Ensino superior ou maior,Solteiro(a),Em dia
8,9,28000.0,2.0,3.0,1.0,28.0,0.0,2257.0,665.8,Feminino,Ensino medio ou menor,Casado(a),Em dia
9,10,4000.0,1.0,3.0,2.0,35.0,-2.0,0.0,0.0,Masculino,Ensino medio ou menor,Solteiro(a),Antecipado

Organizei a base de dados na seguinte ordem: id, limites, sexo2, escolaridade2, status_civil2, idade, pagamento2, valor_divida, valor_pago. Descartei as variáveis sexo, escolaridade, status_civil, e pagamento.

In [7]:
credito = credito[['id', 'limites', 'sexo2', 'escolaridade2', 'status_civil2', 'idade', 'pagamento2', 'valor_divida', 'valor_pago']]
credito.head(10)

,id,limites,sexo2,escolaridade2,status_civil2,idade,pagamento2,valor_divida,valor_pago
0,1,4000.0,Feminino,Ensino superior ou maior,Casado(a),24.0,Atrasado,782.6,0.0
1,2,24000.0,Feminino,Ensino superior ou maior,Solteiro(a),26.0,Antecipado,536.4,0.0
2,3,18000.0,Feminino,Ensino superior ou maior,Solteiro(a),34.0,Em dia,5847.8,303.6
3,4,10000.0,Feminino,Ensino superior ou maior,Casado(a),37.0,Em dia,9398.0,400.0
4,5,10000.0,Masculino,Ensino superior ou maior,Casado(a),57.0,Antecipado,1723.4,400.0
5,6,10000.0,Masculino,Ensino superior ou maior,Solteiro(a),37.0,Em dia,12880.0,500.0
6,7,100000.0,Masculino,Ensino superior ou maior,Solteiro(a),29.0,Em dia,73593.0,11000.0
7,8,20000.0,Feminino,Ensino superior ou maior,Solteiro(a),23.0,Em dia,2375.2,76.0
8,9,28000.0,Feminino,Ensino medio ou menor,Casado(a),28.0,Em dia,2257.0,665.8
9,10,4000.0,Masculino,Ensino medio ou menor,Solteiro(a),35.0,Antecipado,0.0,0.0

Crie a variável debito = valor_divida - valor_pago.

In [8]:
credito['debito'] = credito['valor_divida'] - credito['valor_pago']
credito.head(10)

,id,limites,sexo2,escolaridade2,status_civil2,idade,pagamento2,valor_divida,valor_pago,debito
0,1,4000.0,Feminino,Ensino superior ou maior,Casado(a),24.0,Atrasado,782.6,0.0,782.6
1,2,24000.0,Feminino,Ensino superior ou maior,Solteiro(a),26.0,Antecipado,536.4,0.0,536.4
2,3,18000.0,Feminino,Ensino superior ou maior,Solteiro(a),34.0,Em dia,5847.8,303.6,5544.2
3,4,10000.0,Feminino,Ensino superior ou maior,Casado(a),37.0,Em dia,9398.0,400.0,8998.0
4,5,10000.0,Masculino,Ensino superior ou maior,Casado(a),57.0,Antecipado,1723.4,400.0,1323.4
5,6,10000.0,Masculino,Ensino superior ou maior,Solteiro(a),37.0,Em dia,12880.0,500.0,12380.0
6,7,100000.0,Masculino,Ensino superior ou maior,Solteiro(a),29.0,Em dia,73593.0,11000.0,62593.0
7,8,20000.0,Feminino,Ensino superior ou maior,Solteiro(a),23.0,Em dia,2375.2,76.0,2299.2
8,9,28000.0,Feminino,Ensino medio ou menor,Casado(a),28.0,Em dia,2257.0,665.8,1591.2
9,10,4000.0,Masculino,Ensino medio ou menor,Solteiro(a),35.0,Antecipado,0.0,0.0,0.0

verifiquei quantos clientes possuem débito negativo (ou seja, crédito).

In [9]:
# 8 com o débito negativo
print(credito[credito['debito']<0].shape)
display(credito[credito['debito']<0])

(8, 10)

,id,limites,sexo2,escolaridade2,status_civil2,idade,pagamento2,valor_divida,valor_pago,debito
11,12,52000.0,Feminino,Ensino superior ou maior,Solteiro(a),51.0,Antecipado,2452.2,4363.6,-1911.4
23,24,90000.0,Feminino,Ensino superior ou maior,Casado(a),40.0,Antecipado,1102.4,3885.6,-2783.2
24,25,18000.0,Masculino,Ensino superior ou maior,Solteiro(a),23.0,Em dia,948.8,1151.4,-202.6
26,27,12000.0,Masculino,Ensino superior ou maior,Solteiro(a),27.0,Atrasado,-21.8,0.0,-21.8
28,29,10000.0,Feminino,Ensino medio ou menor,Casado(a),47.0,Antecipado,130.0,683.0,-553.0
30,31,46000.0,Feminino,Ensino superior ou maior,Solteiro(a),27.0,Antecipado,3329.2,3454.0,-124.8
38,39,10000.0,Masculino,Ensino superior ou maior,Solteiro(a),25.0,Atrasado,0.0,156.0,-156.0
39,40,56000.0,Masculino,Ensino superior ou maior,Solteiro(a),31.0,Antecipado,99.6,1815.0,-1715.4

Deixando apenas clientes com débito

In [10]:
print('Antes: ',credito.shape)
credito = credito[credito['debito']>=0]
print('Depois: ',credito.shape)
credito.head(10)

Antes:  (50, 10)
Depois:  (42, 10)

,id,limites,sexo2,escolaridade2,status_civil2,idade,pagamento2,valor_divida,valor_pago,debito
0,1,4000.0,Feminino,Ensino superior ou maior,Casado(a),24.0,Atrasado,782.6,0.0,782.6
1,2,24000.0,Feminino,Ensino superior ou maior,Solteiro(a),26.0,Antecipado,536.4,0.0,536.4
2,3,18000.0,Feminino,Ensino superior ou maior,Solteiro(a),34.0,Em dia,5847.8,303.6,5544.2
3,4,10000.0,Feminino,Ensino superior ou maior,Casado(a),37.0,Em dia,9398.0,400.0,8998.0
4,5,10000.0,Masculino,Ensino superior ou maior,Casado(a),57.0,Antecipado,1723.4,400.0,1323.4
5,6,10000.0,Masculino,Ensino superior ou maior,Solteiro(a),37.0,Em dia,12880.0,500.0,12380.0
6,7,100000.0,Masculino,Ensino superior ou maior,Solteiro(a),29.0,Em dia,73593.0,11000.0,62593.0
7,8,20000.0,Feminino,Ensino superior ou maior,Solteiro(a),23.0,Em dia,2375.2,76.0,2299.2
8,9,28000.0,Feminino,Ensino medio ou menor,Casado(a),28.0,Em dia,2257.0,665.8,1591.2
9,10,4000.0,Masculino,Ensino medio ou menor,Solteiro(a),35.0,Antecipado,0.0,0.0,0.0